### ISSUE TITLE
NW alignment

### ISSUE THREAD

**Issue by evertlammerts** [kortschak/lectures#1]
The recurrence in 02-alignment.slide#12 says to select `max(...)`, should that be `min(...)`?

**Comment by kortschak** [comment]
No, you are wanting to maximise the score for the traversal of the alignment graph. You can see this in the code [here](https://github.com/kortschak/lectures/blob/master/alignment/code/nw.go#L281) and in the equivalent location in SW.

Try running an alignment with the direction being selected as the minimum and see what happens.

**Comment by evertlammerts** [comment]
Ah, that's what I get for scanning instead of reading. I had only seen a
dynamic programming algorithm for computing the NW score that uses a
scoring scheme with positive penalties for indels and mismatches (and a
zero score for matches). In that version the final score corresponds to the
minimum edit distance. Apologies for the noise.
